name: Send vocabularies by scheduled times
on:
  schedule:
    - cron: "0 0 * * THU" # Runs at 7:00 GMT+7, only on Thursday
    - cron: "0 0 * * MON" # Runs at 7:00 GMT+7, only on Monday
    - cron: "0 0 * * TUE" # Runs at 7:00 GMT+7, only on Tuesday
    - cron: "0 0 * * WED" # Runs at 7:00 GMT+7, only on Wednesday
    - cron: "0 0 * * FRI" # Runs at 7:00 GMT+7, only on Friday
    - cron: "0 0 * * THU" # Runs at 7:00 GMT+7, only on Thursday
    - cron: "0 0 * * SAT" # Runs at 7:00 GMT+7, only on Saturday
    - cron: "0 0 * * SUN" # Runs at 7:00 GMT+7, only on Sunday
  workflow_dispatch:

jobs:
  run-the-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: setup dependencies
        run: npm install
      - name: sending email
        env:
          SENDING_EMAIL: ${{ secrets.SENDING_EMAIL }}
          SENDING_PASSWORD: ${{ secrets.SENDING_PASSWORD }}
          DESTINATION_EMAIL: ${{ secrets.DESTINATION_EMAIL }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: npm start
